# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_web_api
    displayName: Build web api
    jobs:
      - job: restore_web_api
        displayName: Restoring packages for web api
        steps:
          - task: DotNetCoreCLI@2
            inputs:
             command: 'restore'
             projects: 'Pipelines.Server/**.csproj'
