trigger:
  batch: true
  branches:
    include:
      - master
      - release/*
    exclude:
      - release/old/*
  paths:
    include:
      - client/pipeline-webpart/*

parameters:
  - name: enableDev
    displayName: Deploy to DEV?
    type: boolean
    default: true
  - name: enableQa
    displayName: Deploy to QA?
    type: boolean
    default: false
  - name: enableProd
    displayName: Deploy to PROD?
    type: boolean
    default: false

variables:
  envDev: DEV
  envQa: QA
  envProd: PROD
  varGroupDev: FrontEnd-DEV
  varGroupQa: FrontEnd-QA
  varGroupProd: FrontEnd-PROD

stages:
  - stage: BuildFrontEnd
    displayName: Build front-end
    jobs:
      - ${{ if eq(parameters['enableDev'], true) }}:
          - template: templates/template-build-environment-package.yml
            parameters:
              environment: ${{ variables.envDev }} # ! NOTE: cannot contain runtime expression $(envDev), template gives error (cannot resolve var name in time)
              varGroupName: ${{ variables.varGroupDev }}

      - ${{ if eq(parameters['enableQa'], true) }}:
          - template: templates/template-build-environment-package.yml
            parameters:
              environment: ${{ variables.envQa }}
              varGroupName: ${{ variables.varGroupQa }}

      - ${{ if eq(parameters['enableProd'], true) }}:
          - template: templates/template-build-environment-package.yml
            parameters:
              environment: ${{ variables.envProd }}
              varGroupName: ${{ variables.varGroupProd }}

  - ${{ if eq(parameters['enableDev'], true) }}:
      - stage: DeployDev
        displayName: "Deploy to DEV"
        condition: succeeded()
        dependsOn: BuildFrontEnd
        variables:
          - group: ${{ variables.varGroupDev }}
        jobs:
          - template: templates/template-deploy.yml
            parameters:
              environment: ${{ variables.envDev }}

  # - ${{ if eq(parameters['enableQa'], true) }}:
  #   - stage: DeployQa
  #     displayName: "Deploy to QA"
  #     condition: succeeded()
  #     dependsOn: BuildFrontEnd
  #     variables:
  #       - group:${{ variables.varGroupQa }}
  #     jobs:
  #       - template: templates/template-deploy.yml
  #         parameters:
  #           environment: ${{ variables.envQa }}

  # - ${{ if eq(parameters['enableProd'], true) }}:
  #   - stage: DeployProd
  #     displayName: "Deploy to Production"
  #     condition: succeeded()
  #     dependsOn:
  #       - ${{ if eq(parameters['enableQa'], true) }}:
  #         - DeployQa
  #       - BuildFrontEnd
  #     variables:
  #       - group:${{ variables.varGroupProd }}
  #     jobs:
  #       - template: templates/template-deploy.yml
  #         parameters:
  #           environment: ${{ variables.envProd }}
