jobs:
  - job: publish_web_api
    displayName: Publish web api
    steps:
    - task: DotNetCoreCLI@2
      displayName: ZIP web api package
      inputs:
        command: publish
        projects: $(projectPath)
        publishWebProjects: True
        arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
        zipAfterPublish: True

    # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
    - task: PublishPipelineArtifact@1
      displayName: Create build artifact
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: $(buildArtifactName)